logging:
  level:
    ROOT: DEBUG
    io.reactivestax: TRACE
    org.springframework: ERROR
    org.springframework.boot.context.config: DEBUG
    org.springframework.data: DEBUG
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE
    org.apache.http.headers: TRACE
    org.apache.http: TRACE
    org.apache.http.wire: TRACE
    org.apache.wss4j: TRACE
pattern:
  console: "%d %-5level %logger : %msg%n"

spring.datasource:
  url: jdbc:mysql://localhost:3306/HoldReleaseDB?serverTimezone=EST5EDT&useSSL=false
  #url: jdbc:mysql://docker-mysql:3307/HoldReleaseDB?serverTimezone=EST5EDT&useSSL=false
  username: root
  password:

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect